### ISSUE TITLE
ViewPager2 nested scroll in parallel doesn't work when SwipeRefreshLayout is in view hierarchy

### ISSUE THREAD

**Issue by RustamG** [android/views-widgets-samples#100]
Hi, 

The [official solution](https://github.com/android/views-widgets-samples/blob/master/ViewPager2/app/src/main/java/androidx/viewpager2/integration/testapp/NestedScrollableHost.kt#L38) to resolve nested scrolling in the same direction as ViewPager2 orientation doesn't work when one of its ancestors is SwipeRefreshLayout.

Here is a diff of the sample to reproduce it: https://github.com/RustamG/views-widgets-samples/commit/3dc2bdf4302a58c1b1de8376224557505a093daa

**Comment by jfresen** [comment]
Hi,

Can you try to see if it works with the latest version of
SwipeRefreshLayout, 1.1.0-alpha04?

**Comment by RustamG** [comment]
1.1.0-alpha04 fails to resolve for me (not yet released?), but with 1.1.0-alpha03 it works in the sample app.
Thanks @jfresen!

**Comment by jfresen** [comment]
Ah, my bad. I was looking at the next version code, not the current version
code. Thanks for sorting that out!
