### ISSUE TITLE
I can't use viewpager2 in fragment ？ 

### ISSUE THREAD

**Issue by Liquidlkw** [android/views-widgets-samples#133]
ViewPager2 viewPager2 = getActivity().findViewById(R.id.vp);
        List<Fragment> fragments = new ArrayList<>();
        fragments.add(new BlankFragment());
        fragments.add(new BlankFragment2());

        viewPager2.setAdapter(new FragmentStateAdapter(this) {
            @NonNull
            @Override
            public Fragment createFragment(int position) {
                return fragments.get(position);
            }

            @Override
            public int getItemCount() {
                return fragments.size();
            }
        });

I code adapter like this in fragment  but is error.
error：
 java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.viewpager2.widget.ViewPager2.setAdapter(androidx.recyclerview.widget.RecyclerView$Adapter)' on a null object reference

How can I do if I want to use vp2 in fragment??

**Comment by Liquidlkw** [comment]
sorry !!!!
I use getActivity().findViewById(R.id.vp);
but vp2 in fragment  
close the issue ,please

**Comment by padilla004828** [comment]
I just want to ask how did you fix it?

**Comment by MarcEntreprend** [comment]
I'm facing the same issue...
