### ISSUE TITLE
androidx.core.widget.NestedScrollView is not scrolling

### ISSUE THREAD

**Issue by DilipSinghPanwar** [android/views-widgets-samples#14]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/background_light"
    android:fitsSystemWindows="false">

    <androidx.core.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/background_screens"
        android:fillViewport="true">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

                <LinearLayout
                    android:id="@+id/appbarlayout"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="@color/colorSearchBackground"
                    android:orientation="vertical">

                    <RelativeLayout
                        android:id="@+id/activity_main"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginBottom="@dimen/margin_10"
                        android:background="@color/colorSearchBackground">

                        <bike.grup.riderapp.utils.CutLayout
                            android:id="@+id/diagonalLayout"
                            android:layout_width="match_parent"
                            android:layout_height="@dimen/_215sdp"
                            android:layout_alignParentStart="true"
                            android:layout_alignParentTop="true">

                            <ImageView
                                android:layout_width="match_parent"
                                android:layout_height="match_parent"
                                android:background="#d4b6b6b6"
                                android:scaleType="centerCrop"
                                app:srcCompat="@drawable/placeholder" />

                        </bike.grup.riderapp.utils.CutLayout>

                        <de.hdodenhof.circleimageview.CircleImageView
                            android:id="@+id/avatar2"
                            android:layout_width="@dimen/_90sdp"
                            android:layout_height="@dimen/_90sdp"
                            android:layout_centerHorizontal="true"
                            android:layout_marginTop="@dimen/_130sdp"
                            android:layout_marginEnd="10dp"
                            android:layout_marginBottom="15dp"
                            android:padding="10dp"
                            android:src="@drawable/feed_profile_image" />

                        <TextView
                            android:id="@+id/title"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_below="@id/avatar2"
                            android:layout_centerHorizontal="true"
                            android:layout_gravity="center|center_vertical"
                            android:layout_marginStart="@dimen/margin_20"
                            android:layout_marginTop="-10dp"
                            android:layout_marginEnd="@dimen/margin_20"
                            android:fontFamily="@font/montserrat_semibold"
                            android:gravity="center_vertical|center"
                            android:padding="5dp"
                            android:text="HOG Baharien Chapter"
                            android:textAllCaps="false"
                            android:textColor="@color/colorPrimary"
                            android:textSize="15sp"
                            android:textStyle="bold" />

                        <TextView
                            android:id="@+id/subtitle"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_below="@id/title"
                            android:layout_centerHorizontal="true"
                            android:layout_gravity="center|center_vertical"
                            android:layout_marginStart="@dimen/margin_20"
                            android:layout_marginTop="3dp"
                            android:layout_marginEnd="@dimen/margin_20"
                            android:fontFamily="@font/montserrat_regular"
                            android:gravity="center_vertical|center"
                            android:text="Bahrains Official Harley Davision Riding Club"
                            android:textAllCaps="false"
                            android:textColor="#767676"
                            android:textSize="13sp" />

                    </RelativeLayout>

                </LinearLayout>

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical">

                <com.google.android.material.tabs.TabLayout
                    android:id="@+id/tabs"
                    android:layout_width="match_parent"
                    android:layout_height="@dimen/_40sdp"
                    android:background="@color/colorSearchBackground"
                    app:tabGravity="fill"
                    app:tabIndicatorColor="#000000"
                    app:tabMode="fixed"
                    app:tabTextAppearance="@style/MineCustomTabText"
                    app:tabTextColor="#000000" />

                <bike.grup.riderapp.utils.NonSwipeableViewPager
                    android:id="@+id/viewpager"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content" />

            </LinearLayout>

        </LinearLayout>

    </androidx.core.widget.NestedScrollView>

</LinearLayout>

**Comment by fc9734ygn** [comment]
I don't think you should set the android:layout_height of NestedScrollView child to match_parent it should be wrap_content

**Comment by raghunandankavi2010** [comment]
Any update on this?
